---
title: "5 Interesting R Examples"
author: "Sefa Erbas - BDA 503 - Fall 2017"
output: html_document
---


1. [Elegant Graphics in “R”](http://zevross.com/blog/2014/08/04/beautiful-plotting-in-r-a-ggplot2-cheatsheet-3/)

    This pages gives detail information about “R” ggplot2 library which provides to create elegant graphics.
    

2. [“R” concept](https://www.programiz.com/r-programming)

    This article can be described as “R for beginners” that gives clear answers for the new users as understanding its concept. “R” has been defined as simple expressive syntax and easy-to-use interface, also gives an interesting example using graphics.


3. [Favorite “R” Packages](http://bitesizebio.com/23003/my-10-favorite-r-packages-and-the-cool-things-you-can-do-with-them/)

    A “R” master has shared his favorite R packages that can be used in Visualization, statistical analysis, Data Wrangling, Bioinformatics and sharing.


4. [Useful Data to Work Wtih](https://r-dir.com/reference/datasets.html)

    This articale gives useful links for handful of sources for data to work with.


5. [Data Analysis](http://www.css.cornell.edu/faculty/dgr2/teach/R/R_corregr.pdf)

    This tutorial presents a data analysis sequence which may be applied to environmental datasets, using a small but typical data set of multivariate point observations.


